name: Staging Deployment

on:
  push:
    branches:
      - hemant

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
         ssh-private-key: ${{ secrets.KEY }}
        # You'll need to add the corresponding public key to your AWS server's authorized_keys files

      - name: Deploy to AWS
        run: |
         ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/ ubuntu@3.138.33.29 "
         cd /var/www/html/new
         sudo git pull origin hemant "
